version: '2'
services:
    aspnetcore-webapi:
        build:
            dockerfile: ./${DOCKER_FILE}
            context: .
        image: core/aspnetcore-webapi
        container_name: aspnetcore-webapi-${STAGE}
        environment: 
          AMBIENTE: ${STAGE}
        ports:
            - "${PORT}:80"